version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
    overwrite: true
file_exists_behavior: OVERWRITE


permissions:
  - object: /
    pattern: "**"
    owner: apache
    group: apache


hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root

